# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=10, unique=True, verbose_name='Guru')),
                ('nama', models.CharField(max_length=100, null=True, verbose_name='Guru')),
                ('tanggal_lahir', models.DateField(help_text='Format Tanggal: YYYY-MM-DD', verbose_name='Tanggal Lahir')),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default='Laki-laki', max_length=10, verbose_name='Jenis Kelamin')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
            ],
            options={
                'verbose_name_plural': 'Guru',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=10, unique=True, verbose_name='Guru')),
                ('nama', models.CharField(max_length=100, null=True, verbose_name='Guru')),
                ('tanggal_lahir', models.DateField(help_text='Format Tanggal: YYYY-MM-DD', verbose_name='Tanggal Lahir')),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default='Laki-laki', max_length=10, verbose_name='Jenis Kelamin')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
            ],
            options={
                'verbose_name_plural': 'Siswa',
            },
        ),
    ]
