# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolahapp', '0002_auto_20170908_1022'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guru',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='guru',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='guru',
            name='tanggal_lahir',
        ),
        migrations.AddField(
            model_name='guru',
            name='mapel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolahapp.MataPelajaran'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='jurusan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolahapp.Jurusan'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1, verbose_name='Kelas'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='mapel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolahapp.MataPelajaran'),
        ),
        migrations.AlterField(
            model_name='guru',
            name='nama',
            field=models.CharField(max_length=100, null=True, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='guru',
            name='nip',
            field=models.CharField(max_length=10, unique=True, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nama',
            field=models.CharField(max_length=100, null=True, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.CharField(max_length=10, unique=True, verbose_name='NIS'),
        ),
    ]
