# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolahapp', '0002_auto_20170908_1022'),
        ('userapp', '0002_auto_20170908_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='mapel',
        ),
        migrations.AddField(
            model_name='siswa',
            name='mapel',
            field=models.ManyToManyField(null=True, to='sekolahapp.MataPelajaran'),
        ),
    ]
